/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface CloudflareEnv cloudflare-env.d.ts` (hash: 11e566693ea11dc8027100b2e814ed6d)
interface __BaseEnv_CloudflareEnv {
	PAYMENT_RECOVERY_QUEUE: Queue;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	SITE_URL: "https://mubendecountryresort.mubendecountryresort.workers.dev";
	PESAPAL_CONSUMER_KEY: string;
	PESAPAL_CONSUMER_SECRET: string;
	PESAPAL_BASE_URL: string;
	DATABASE_URL: string;
	PAYMENT_RECOVERY_QUEUE_SECRET: string;
	NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./worker").default>;
	PAYMENT_RECONCILER: Fetcher /* mcr-payment-reconciler */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "PESAPAL_CONSUMER_KEY" | "PESAPAL_CONSUMER_SECRET" | "PESAPAL_BASE_URL" | "DATABASE_URL" | "PAYMENT_RECOVERY_QUEUE_SECRET" | "NEXT_PUBLIC_TURNSTILE_SITE_KEY" | "TURNSTILE_SECRET_KEY">> {}
}
