/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --config wrangler.reconciler.jsonc --env-interface PaymentReconcilerEnv payment-reconciler-env.d.ts` (hash: 2721dc14301d937b1a96ad6471c23859)
interface __BaseEnv_PaymentReconcilerEnv {
	PAYMENT_RECOVERY_QUEUE: Queue;
	PESAPAL_CONSUMER_KEY: string;
	PESAPAL_CONSUMER_SECRET: string;
	PESAPAL_BASE_URL: string;
	DATABASE_URL: string;
	PAYMENT_RECOVERY_QUEUE_SECRET: string;
	NEXT_PUBLIC_TURNSTILE_SITE_KEY: string;
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/payment-reconciler");
	}
	interface Env extends __BaseEnv_PaymentReconcilerEnv {}
}
interface PaymentReconcilerEnv extends __BaseEnv_PaymentReconcilerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PESAPAL_CONSUMER_KEY" | "PESAPAL_CONSUMER_SECRET" | "PESAPAL_BASE_URL" | "DATABASE_URL" | "PAYMENT_RECOVERY_QUEUE_SECRET" | "NEXT_PUBLIC_TURNSTILE_SITE_KEY" | "TURNSTILE_SECRET_KEY">> {}
}
